version: '3'

services:
  node1:
    image: funkypenguin/bloc
    container_name: bloctest-node1
    volumes:
      - ../blocd:/var/lib/blocd/
    networks:
      testnet:
        ipv4_address: 172.16.76.11
  
#  node2:
#    image: funkypenguin/bloc
#    container_name: bloctest-node2
#    networks:
#      testnet:
#        ipv4_address: 172.16.76.12
  
#  node3:
#    image: funkypenguin/bloc
#    container_name: bloctest-node3
#    networks:
#      testnet:
#        ipv4_address: 172.16.76.13

networks:
  testnet:
    ipam:
      config:
        - subnet: 172.16.76.0/24

